name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.3'

      - name: Run test
        run: |
          go test ./...
